config/routes.rb
Rails.application.routes.draw do
  resources :password_resets, only: [:create, :edit, :update, :new]
  mount Resque::Server.new, at: '/resque'

  root 'static#home'

  get 'login', to: 'user_sessions#new', as: 'login'
  resource :user_sessions

  resource :team, only: [:new, :create]

  namespace :public do
    resources :releases, only: [:index, :show], param: :public_id
    resources :subscription, only: [:new, :create]
    resources :pubframe, only: [:index]
    resource :error, only: [:show]
    resources :summary, only: [:show]
  end

  namespace :api do
    resources :projects, only: [:show], param: :public_key do
      resources :releases, only: [:index]
      resources :email_subscriptions, only: [:index, :create, :destroy]
      resources :uref_info, path: 'uref-info', only: [:show]
    end
  end

  resources :public_form, only: [:show, :create]

  resources :users, only: [:index, :new, :create, :destroy]
  resource :api_settings, only: [:show]
  resource :ghhook, only: [:create]
  resource :emailhook, only: [:create]

  resource :dashboard, only: [:show]

  resources :projects, only: [:index, :create, :destroy, :new], param: :public_id do
    get 'inbox'
    resources 'prompt_history', only: [:index]
    get 'releases'

    resources :releases, param: :public_id


    resource :settings, only: [:edit, :update] do
      resource :prompt_invitation_token, only: [:new,:create]
      resources :categories, only: [:index, :new, :create, :destroy]
      resources :subscriptions, only: [:index, :create, :destroy, :new, :edit, :update]
      resources :prompt_subscripts, only: [:index, :new, :destroy]
      resources :github_prompt, only: [:new, :create]

      resources :submission_form_prompt, only: [:new, :create, :edit, :update] do
        resources :form_prompt_emails, only: [:new, :create, :destroy]
      end

      resources :public_form_prompt, only: [:new, :create, :edit, :update]

      resources :email_prompt, only: [:new, :create]
      resource :prompt, only: [:new]
      resources :release_robot_prompt, only: [:new, :create]
      resource :feed, only: [:show, :update]
      resources :project_users, only: [:index, :create, :destroy]
    end

    post 'update_settings'
    post 'send_release'
    resources :release_set, only: [:show] do
      get 'resend'
    end

    resource :prompts, only: [:edit, :update] do
      put 'discard'
      get 'edit_release'
      put 'send_to_inbox'
      post 'create_release'
    end
    post 'hook'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :project
  before_create :generate_public

  def generate_public
    self.public_key = SecureRandom.hex(10)
  end
end

app/models/commit.rb
class Commit < ApplicationRecord
  belongs_to :prompt
end

app/models/email_prompt_detail.rb
class EmailPromptDetail < ApplicationRecord
  belongs_to :prompt
end

app/models/email_subscription.rb
class EmailSubscription < ApplicationRecord
  belongs_to :project
  enum kind: { schedule: 0 , instant: 1 }
  enum interval_type: { hours: 0, days: 1 , weeks: 2 }
  default_scope { where('email_subscriptions.active = true') }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :prompts
  has_many :prompt_subscriptions
  has_many :email_subscriptions
  has_many :releases
  has_many :project_users
  has_many :categories
  before_create :generate_public
  belongs_to :team

  scope :active, -> { where('projects.active = true') }

  def generate_public
    self.public_key = SecureRandom.hex(10) if !self.public_key
  end

end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  class LastRecordError < StandardError; end

  belongs_to :project
  belongs_to :user
  before_destroy :check_last_record

  private

  def check_last_record
    raise LastRecordError.new("You cannot delete the last project user") if last_record?
  end

  def last_record?
    project.project_users.count === 1
  end
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  enum status: { pending: 0 , complete: 1 }
  enum kind: {
         github_commit: 0 ,
         github_pull_request: 1,
         release_robot: 2,
         email: 3,
         submission_form: 4,
         public_form: 5
       }
  belongs_to :project
  belongs_to :form_prompt_subscription_reminder, optional: true
  has_many :releases
  has_one :commit
  has_one :email_prompt_detail
  belongs_to :internal_prompt_release, class_name: 'Release', foreign_key: 'internal_prompt_release_id', optional: true
  belongs_to :prompt_subscription, optional: true
end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
  belongs_to :project
end

app/models/push.rb
class Push < ApplicationRecord
  enum status: [:not_released, :released, :discarded]
  belongs_to :project
  belongs_to :pull_request, optional: true, class_name: 'PullRequest', primary_key: 'sha', foreign_key: 'sha'
  has_many :releases
end

app/models/release.rb
class Release < ApplicationRecord
  default_scope { where('active = true') }
  enum status: [:draft, :published]
  has_one :push
  belongs_to :category, optional: true
  belongs_to :project
  belongs_to :user
end

app/models/release_read.rb
class ReleaseRead < ApplicationRecord
  belongs_to :release
  belongs_to :uref
end

app/models/release_set.rb
class ReleaseSet < ApplicationRecord
  belongs_to :project
end

app/models/summary.rb
class Summary < ApplicationRecord
  belongs_to :email_subscription
  has_many :summary_releases
  has_many :releases, through: :summary_releases
end

app/models/summary_release.rb
class SummaryRelease < ApplicationRecord
  belongs_to :summary
  belongs_to :release
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users
  has_many :projects
end

app/models/uref.rb
class Uref < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  attr_accessor :password, :password_confirmation
  belongs_to :team

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/shared/_dash_menu.html.erb
<h1><%= @facade.team.name %></h1>
<%= render 'components/tabs',
menu_items: {
  'Users' => { path: users_path },
  'API' => { path: api_settings_path }
}
%>

app/views/shared/_email_sub_form.html.erb
<script>

 $( document ).ready(function() {

   $('#start-date').datepicker({
     dateFormat: 'dd/mm/yy'
   });

   $('#start-time').timepicker({
     timeFormat: 'h:mm p',
     interval: 30,
     dynamic: false,
     dropdown: true,
     scrollbar: true
   });

 });
</script>


<div id="form-errors"></div>
<% if local_assigns.fetch(:email_field, true) %>
  <div class="form-group required">
    <%= f.label :email, class: "control-label" %>
    <%= f.email_field :email, class: "form-control", required: true, id: 'email', placeholder: 'Email address to subscribe' %>
  </div>
<% end %>


<h3><%= local_assigns.fetch(:interval_message, 'How often would you like to be updated?') %></h3>

<div class="form-group required">
  <%= f.label :interval_value, 'Every', class: "control-label" %>
  <div class="grid-12-fields">
    <div style="grid-column: span 6;">
      <%= f.number_field :interval_value, class: "form-control", required: true, placeholder: 'Interval - e.g. 1', id: 'interval-value', min: 0, oninput: "this.value = Math.abs(this.value)" %>
    </div>

    <div style="grid-column: span 6;">
      <%= f.select :interval_type, options_for_select(['hours', 'days'], @facade.form.interval_type), { prompt: 'Please Select' }, class: "form-control", required: true, id: 'interval-type' %>
    </div>
  </div>
</div>

<div class="form-group required">
  <%= f.label :email, 'Starting From', class: "control-label" %>

  <div class="grid-12-fields">
    <div style="grid-column: span 6;">
      <%= f.text_field :start_date, value: @facade.form.split_date, class: "form-control", required: true, id: 'start-date', placeholder: 'Date' %>
    </div>

    <div style="grid-column: span 6;">
      <%= f.text_field :start_time, value: @facade.form.split_time, class: "form-control", required: true, id: 'start-time', placeholder: 'Time' %>
    </div>
  </div>
</div>

app/views/shared/_form_errors.html.erb
<% if form.errors.any? %>
  <div class="alert alert-danger form-errors">
    <h4><%= pluralize(form.errors.count, "error") %> prohibited this from being saved:</h4>
    <ul>
      <% form.errors.full_messages.each do |message|  %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<% if content_for?(:title) %>
  <title><%= yield(:title) %> | ReleaseNet </title>
<% else %>
  <title>ReleaseNet </title>
<% end %>

<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600" rel="stylesheet">
<%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.css' %>
<%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.js' %>
<%= javascript_include_tag 'https://unpkg.com/micromodal/dist/micromodal.min.js' %>
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<%= favicon_link_tag asset_path('favicon.svg') %>
<%= render 'layouts/flash_rendering_toastr' %>

<script src="https://unpkg.com/popper.js@1"></script>
<script src="https://unpkg.com/tippy.js@4"></script>

app/views/shared/_modal.html.erb
<div class="modal micromodal-slide" id="modal-1" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
      <header class="modal__header">
          <h2 class="modal-title" style="margin-top: 0px; margin-bottom: 0px;"><%= title %></h2>
        <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
      </header>
      <main class="modal__content" id="modal-1-content">
        <%= yield %>
      </main>
      <footer class="modal__footer">
      </footer>
    </div>
  </div>
</div>

app/views/shared/_nav_brand.html.erb
<div class="rr-nav-brand">
  <div style="display: flex; align-items: center;">
    <%= link_to dashboard_path do %>
      <%= image_tag 'logo-small.png', style: 'width: 204px;' %>
    <% end %>
    <span id="updates-indicator" style="display: none">Updates<span id="unread-count"></span></span>
  </div>
</div>

app/views/shared/_no_email_subscription_instruction.html.erb
<div style="text-align: center;">
<%= image_tag 'badge-bw.svg', style: 'margin-top: 30px' %>
<h3>
You don't have any email subscriptions yet
    </h3>
    <p>An email subscriber will receive periodic updates of all releases in this project.</p>
    <p>This is handy because they do not need to continually check the feed for updates.</p>
  </br>
  <%= link_to new_project_settings_subscription_path, class: 'btn btn-secondary', style: 'margin-left: 9px', remote: true do %>
<i class="fas fa-plus"></i>&nbsp
Add a subscription
  <% end %>
</div>

app/views/shared/_no_prompts_instruction.html.erb
<div style="text-align: center;">
<%= image_tag 'badge-bw.svg', style: 'margin-top: 30px' %>
<h3>
You don't have any prompts setup yet
    </h3>
    <p>A prompt allows you to 'subscribe' your project to an outside source.</p>
    <p>Prompts are the best way to ensure you communicate consistently with your audience.</p>
  </br>
  <%= link_to new_project_settings_prompt_subscript_path, class: 'btn btn-secondary', style: 'margin-left: 9px'  do %>
<i class="fas fa-plus"></i>&nbsp
Add a Prompt
  <% end %>

  <%= link_to Constants::PROMPT_INFORMATION_LINK, class: 'btn btn-tertiary', style: 'margin-left: 9px', target: '_blank' do %>
<i class="fa fa-question-circle"></i>&nbsp
More information
  <% end %>
</div>

app/views/shared/_project_menu.html.erb
<div style="display: flex; justify-content: space-between;">
  <h1> <%= @current_project.title.truncate(40) %> </h1>
  <%= link_to public_releases_url(p: @facade.project.public_key), class: 'btn btn-primary', style: 'align-self: center;', target: '_blank' do %>
    <i class="fas fa-stream"></i>&nbsp&nbsp
    View Feed
  <% end %>
</div>

<%= render 'components/tabs',
menu_items: {
  'Releases' => { path: project_releases_path },
  'Project Settings' => { path: edit_project_settings_path, url_active_regex: /settings/ },
},
activate_regex: /settings/
%>

app/views/shared/_project_visibility_tooltip.html.erb
<script>
 $(document).ready(function() {
   tippy('#visibility-help', {
     content: 'This determines if the feed for this project is public or private. Private projects require the user to be logged into a ReleaseNet account on your team before viewing the feed.',
     placement: 'bottom',
   })
 });
</script>

app/views/shared/_prompts_menu.html.erb
<%= render 'components/tabs',
menu_items: {
  'Inbox' => { path: project_inbox_path }, 'History' => { path: project_prompt_history_index_path }
}
%>

app/views/shared/_pushes_table.html.erb
<table class="rr-table ">

  <thead>
    <th>Date</th>
    <th>Type</th>
    <th>Title</th>
    <th></th>
  </thead>

  <% @facade.prompts.each do |prompt| %>
    <tr>
      <td width="15%"><%= Tznet::Format.run('au_datetime', Tznet::Parse::FromI.run(prompt.created_at)) %></td>
      <td width="15%"><%= prompt.kind.titleize %></td>
      <td width=""><%= prompt.title.truncate(50) %></td>

      <% if show_create_release %>
        <td width="20%"><%= link_to 'Create Release', new_project_release_path(pid: prompt.id) %></td>
      <% end %>

      <% if show_delete %>
        <td width="10%">
          <%= link_to discard_project_prompts_path(prompt_id: prompt.id), method: :put, id: 'discard', data: { confirm: 'Are you sure you want to discard this prompt?' } do %>
            <i class="fa fa-times-circle"></i>
          <% end %>
        </td>
      <% end %>

      <% if show_revert %>
        <td width="20%">
          <%= link_to send_to_inbox_project_prompts_path(prompt_id: prompt.id), method: :put  do %>
            <i class="fa fa-undo"></i> Send to Inbox
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>