config/routes.rb
Rails.application.routes.draw do
  resources :password_resets, only: [:create, :edit, :update, :new]
  mount Resque::Server.new, at: '/resque'

  root 'static#home'

  get 'login', to: 'user_sessions#new', as: 'login'
  resource :user_sessions

  resource :team, only: [:new, :create]

  namespace :public do
    resources :releases, only: [:index, :show], param: :public_id
    resources :subscription, only: [:new, :create]
    resources :pubframe, only: [:index]
    resource :error, only: [:show]
    resources :summary, only: [:show]
  end

  namespace :api do
    resources :projects, only: [:show], param: :public_key do
      resources :releases, only: [:index]
      resources :email_subscriptions, only: [:index, :create, :destroy]
      resources :uref_info, path: 'uref-info', only: [:show]
    end
  end

  resources :public_form, only: [:show, :create]

  resources :users, only: [:index, :new, :create, :destroy]
  resource :api_settings, only: [:show]
  resource :ghhook, only: [:create]
  resource :emailhook, only: [:create]

  resource :dashboard, only: [:show]

  resources :projects, only: [:index, :create, :destroy, :new], param: :public_id do
    get 'inbox'
    resources 'prompt_history', only: [:index]
    get 'releases'

    resources :releases, param: :public_id


    resource :settings, only: [:edit, :update] do
      resource :prompt_invitation_token, only: [:new,:create]
      resources :categories, only: [:index, :new, :create, :destroy]
      resources :subscriptions, only: [:index, :create, :destroy, :new, :edit, :update]
      resources :prompt_subscripts, only: [:index, :new, :destroy]
      resources :github_prompt, only: [:new, :create]

      resources :submission_form_prompt, only: [:new, :create, :edit, :update] do
        resources :form_prompt_emails, only: [:new, :create, :destroy]
      end

      resources :public_form_prompt, only: [:new, :create, :edit, :update]

      resources :email_prompt, only: [:new, :create]
      resource :prompt, only: [:new]
      resources :release_robot_prompt, only: [:new, :create]
      resource :feed, only: [:show, :update]
      resources :project_users, only: [:index, :create, :destroy]
    end

    post 'update_settings'
    post 'send_release'
    resources :release_set, only: [:show] do
      get 'resend'
    end

    resource :prompts, only: [:edit, :update] do
      put 'discard'
      get 'edit_release'
      put 'send_to_inbox'
      post 'create_release'
    end
    post 'hook'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :project
  before_create :generate_public

  def generate_public
    self.public_key = SecureRandom.hex(10)
  end
end

app/models/commit.rb
class Commit < ApplicationRecord
  belongs_to :prompt
end

app/models/email_prompt_detail.rb
class EmailPromptDetail < ApplicationRecord
  belongs_to :prompt
end

app/models/email_subscription.rb
class EmailSubscription < ApplicationRecord
  belongs_to :project
  enum kind: { schedule: 0 , instant: 1 }
  enum interval_type: { hours: 0, days: 1 , weeks: 2 }
  default_scope { where('email_subscriptions.active = true') }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :prompts
  has_many :prompt_subscriptions
  has_many :email_subscriptions
  has_many :releases
  has_many :project_users
  has_many :categories
  before_create :generate_public
  belongs_to :team

  scope :active, -> { where('projects.active = true') }

  def generate_public
    self.public_key = SecureRandom.hex(10) if !self.public_key
  end

end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  class LastRecordError < StandardError; end

  belongs_to :project
  belongs_to :user
  before_destroy :check_last_record

  private

  def check_last_record
    raise LastRecordError.new("You cannot delete the last project user") if last_record?
  end

  def last_record?
    project.project_users.count === 1
  end
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  enum status: { pending: 0 , complete: 1 }
  enum kind: {
         github_commit: 0 ,
         github_pull_request: 1,
         release_robot: 2,
         email: 3,
         submission_form: 4,
         public_form: 5
       }
  belongs_to :project
  belongs_to :form_prompt_subscription_reminder, optional: true
  has_many :releases
  has_one :commit
  has_one :email_prompt_detail
  belongs_to :internal_prompt_release, class_name: 'Release', foreign_key: 'internal_prompt_release_id', optional: true
  belongs_to :prompt_subscription, optional: true
end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
  belongs_to :project
end

app/models/push.rb
class Push < ApplicationRecord
  enum status: [:not_released, :released, :discarded]
  belongs_to :project
  belongs_to :pull_request, optional: true, class_name: 'PullRequest', primary_key: 'sha', foreign_key: 'sha'
  has_many :releases
end

app/models/release.rb
class Release < ApplicationRecord
  default_scope { where('active = true') }
  enum status: [:draft, :published]
  has_one :push
  belongs_to :category, optional: true
  belongs_to :project
  belongs_to :user
end

app/models/release_read.rb
class ReleaseRead < ApplicationRecord
  belongs_to :release
  belongs_to :uref
end

app/models/release_set.rb
class ReleaseSet < ApplicationRecord
  belongs_to :project
end

app/models/summary.rb
class Summary < ApplicationRecord
  belongs_to :email_subscription
  has_many :summary_releases
  has_many :releases, through: :summary_releases
end

app/models/summary_release.rb
class SummaryRelease < ApplicationRecord
  belongs_to :summary
  belongs_to :release
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users
  has_many :projects
end

app/models/uref.rb
class Uref < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  attr_accessor :password, :password_confirmation
  belongs_to :team

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/settings_controller.rb
class SettingsController < SettingsBaseController
  layout 'backstage_bare'
  def edit
    @facade = Settings::EditFacade.new(params)
  end

  def update
    SettingsForm.new(
      params[:settings_form]
        .permit(:title, :emails, :public_feed, :hide_author, :visibility)
        .merge({pid: params[:project_public_id]})
    ).save

    flash[:success] = 'Details Saved Successfully'
    redirect_page_js edit_project_settings_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/settings/_settings_menu.html.erb
<%= render 'components/tabs',
menu_items: {
  'Details' => { path: edit_project_settings_path },
  'Categories' => { path: project_settings_categories_path },
  'Access' => { path: project_settings_project_users_path }
}
%>

app/views/settings/edit.html.erb
<%= render 'shared/project_menu' %>

<% content_for :title do %>
  Settings
<% end %>


<%= render 'shared/project_visibility_tooltip' %>

<div id="modal-container"></div>

<%= render 'settings_menu' %>

<div class="settings-details-tab">
  <div class="details-form">
    <div style="display: flex; justify-content: space-between; align-items: baseline;">

      <div>

        <h2 style="margin-bottom: 0">Project Details</h3>
          <p style="color: #bcbcbc; margin-top: 0;"><strong>Project ID:</strong> <%= @current_project.public_key %></p> &nbsp&nbsp
      </div>

      <div style="display: flex; align-items: center;">
        <%= button_to 'Delete Project', project_path(public_id: @facade.project.public_key), method: :delete, class: 'btn btn-secondary btn-danger', data: { confirm: 'Are you sure you want to delete this project?' } %>
      </div>

    </div>


    <%= form_for @facade.form, url: project_settings_path, remote: true, method: :put do |f| %>
      <div id="form-errors"></div>

      <div class="form-group required">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :title, class: "form-control", required: true, style: 'width: 50%' %>
      </div>

      <div class="form-group">
        <%= label_tag :visibility, 'Type', class: 'control-label' %>
        <%= link_to '#', class: '', style: 'margin-left: 5px', target: '_blank', id: 'visibility-help' do %>
          <i class="fa fa-question-circle"></i>&nbsp
        <% end %>
        <%= f.select :visibility, options_for_select(['Private', 'Public'], @facade.project.public_feed ? 'Public' : 'Private'), {} ,class: 'form-control', style: 'width: 50%'  %>

      </div>

      <h3>Feed Settings</h3>

      <div class="form-group">
        <%= f.label :hide_author, class: 'control-label' do %>
          <%= f.check_box :hide_author %>
          Hide Release Author
        <% end %>
      </div>

      <div class="form-group">
        <%= button_tag(name: 'commit', value: 'create', :class => "btn btn-secondary") do %>
          <i class="fas fa-save"></i>&nbsp
          Save
        <% end %>
      </div>
    <% end %>


    <% unless @facade.subscribed.empty? %>
      <h2>Connected Projects</h2>

      <ul>
        <% @facade.subscribed.each do |subscribed_project| %>
          <li>
            <%= subscribed_project.title %>
          </li>
        <% end %>
      </ul>

    <% end %>
  </div>

  <div class="invite-form">
  </div>

</div>