config/routes.rb
Rails.application.routes.draw do
  resources :password_resets, only: [:create, :edit, :update, :new]
  mount Resque::Server.new, at: '/resque'

  root 'static#home'

  get 'login', to: 'user_sessions#new', as: 'login'
  resource :user_sessions

  resource :team, only: [:new, :create]

  namespace :public do
    resources :releases, only: [:index, :show], param: :public_id
    resources :subscription, only: [:new, :create]
    resources :pubframe, only: [:index]
    resource :error, only: [:show]
    resources :summary, only: [:show]
  end

  namespace :api do
    resources :projects, only: [:show], param: :public_key do
      resources :releases, only: [:index]
      resources :email_subscriptions, only: [:index, :create, :destroy]
      resources :uref_info, path: 'uref-info', only: [:show]
    end
  end

  resources :public_form, only: [:show, :create]

  resources :users, only: [:index, :new, :create, :destroy]
  resource :api_settings, only: [:show]
  resource :ghhook, only: [:create]
  resource :emailhook, only: [:create]

  resource :dashboard, only: [:show]

  resources :projects, only: [:index, :create, :destroy, :new], param: :public_id do
    get 'inbox'
    resources 'prompt_history', only: [:index]
    get 'releases'

    resources :releases, param: :public_id


    resource :settings, only: [:edit, :update] do
      resource :prompt_invitation_token, only: [:new,:create]
      resources :categories, only: [:index, :new, :create, :destroy]
      resources :subscriptions, only: [:index, :create, :destroy, :new, :edit, :update]
      resources :prompt_subscripts, only: [:index, :new, :destroy]
      resources :github_prompt, only: [:new, :create]

      resources :submission_form_prompt, only: [:new, :create, :edit, :update] do
        resources :form_prompt_emails, only: [:new, :create, :destroy]
      end

      resources :public_form_prompt, only: [:new, :create, :edit, :update]

      resources :email_prompt, only: [:new, :create]
      resource :prompt, only: [:new]
      resources :release_robot_prompt, only: [:new, :create]
      resource :feed, only: [:show, :update]
      resources :project_users, only: [:index, :create, :destroy]
    end

    post 'update_settings'
    post 'send_release'
    resources :release_set, only: [:show] do
      get 'resend'
    end

    resource :prompts, only: [:edit, :update] do
      put 'discard'
      get 'edit_release'
      put 'send_to_inbox'
      post 'create_release'
    end
    post 'hook'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :project
  before_create :generate_public

  def generate_public
    self.public_key = SecureRandom.hex(10)
  end
end

app/models/commit.rb
class Commit < ApplicationRecord
  belongs_to :prompt
end

app/models/email_prompt_detail.rb
class EmailPromptDetail < ApplicationRecord
  belongs_to :prompt
end

app/models/email_subscription.rb
class EmailSubscription < ApplicationRecord
  belongs_to :project
  enum kind: { schedule: 0 , instant: 1 }
  enum interval_type: { hours: 0, days: 1 , weeks: 2 }
  default_scope { where('email_subscriptions.active = true') }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :prompts
  has_many :prompt_subscriptions
  has_many :email_subscriptions
  has_many :releases
  has_many :project_users
  has_many :categories
  before_create :generate_public
  belongs_to :team

  scope :active, -> { where('projects.active = true') }

  def generate_public
    self.public_key = SecureRandom.hex(10) if !self.public_key
  end

end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  class LastRecordError < StandardError; end

  belongs_to :project
  belongs_to :user
  before_destroy :check_last_record

  private

  def check_last_record
    raise LastRecordError.new("You cannot delete the last project user") if last_record?
  end

  def last_record?
    project.project_users.count === 1
  end
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  enum status: { pending: 0 , complete: 1 }
  enum kind: {
         github_commit: 0 ,
         github_pull_request: 1,
         release_robot: 2,
         email: 3,
         submission_form: 4,
         public_form: 5
       }
  belongs_to :project
  belongs_to :form_prompt_subscription_reminder, optional: true
  has_many :releases
  has_one :commit
  has_one :email_prompt_detail
  belongs_to :internal_prompt_release, class_name: 'Release', foreign_key: 'internal_prompt_release_id', optional: true
  belongs_to :prompt_subscription, optional: true
end

app/models/prompt_subscription.rb
class PromptSubscription < ApplicationRecord
  belongs_to :project
  has_one :github_prompt_subscription
  has_one :internal_prompt_subscription
  has_one :email_prompt_subscription
  has_one :form_prompt_subscription
  enum kind: { release_robot: 0, github: 1, email: 2, submission_form: 3, public_form: 4 }

  scope :active, -> { where('prompt_subscriptions.deleted = false') }
end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
  belongs_to :project
end

app/models/push.rb
class Push < ApplicationRecord
  enum status: [:not_released, :released, :discarded]
  belongs_to :project
  belongs_to :pull_request, optional: true, class_name: 'PullRequest', primary_key: 'sha', foreign_key: 'sha'
  has_many :releases
end

app/models/release.rb
class Release < ApplicationRecord
  default_scope { where('active = true') }
  enum status: [:draft, :published]
  has_one :push
  belongs_to :category, optional: true
  belongs_to :project
  belongs_to :user
end

app/models/release_read.rb
class ReleaseRead < ApplicationRecord
  belongs_to :release
  belongs_to :uref
end

app/models/release_set.rb
class ReleaseSet < ApplicationRecord
  belongs_to :project
end

app/models/summary.rb
class Summary < ApplicationRecord
  belongs_to :email_subscription
  has_many :summary_releases
  has_many :releases, through: :summary_releases
end

app/models/summary_release.rb
class SummaryRelease < ApplicationRecord
  belongs_to :summary
  belongs_to :release
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users
  has_many :projects
end

app/models/uref.rb
class Uref < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  attr_accessor :password, :password_confirmation
  belongs_to :team

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/api/projects_controller.rb
module Api
  class ProjectsController < ApplicationController
    skip_before_action :require_login, only:[:home]
  end
end

app/controllers/feeds_controller.rb
class FeedsController < SettingsBaseController
  layout 'backstage_bare'
  def show
    project = Project.find(params[:project_id])
    @facade = OpenStruct.new(
      project: project,
      form: FeedSettingsForm.new(project.attributes)
    )
  end

  def update
    FeedSettingsForm.new(params[:feed_settings_form].merge(project_id: params[:project_id])).save
    flash[:success] = 'Feed settings updated'
    redirect_to(fallback_location: root_path)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ProjectsBaseController
  skip_before_action :verify_project_ownership, only: [:index, :create, :hook, :new]

  layout 'backstage_bare', except: [:index]

  def index
    projects = ProjectsForUser.new(current_user).run
    @facade = OpenStruct.new(
      projects: projects,
      team: current_user.team,
      unread_counts: UnactionedPromptCounter.new(projects).run
    )
    render layout: "backstage_bare"
  end

  def new

  end

  def create
    project = Project.create!(
      title: params[:name],
      team: current_user.team,
      public_feed: params[:visibility] == 'Public'
    )
    project.project_users.create(user_id: current_user.id)

    flash[:success] = 'Project created'
    return redirect_to dashboard_path
  end

  def inbox
    @facade = Projects::InboxFacade.new(params)
  end

  def destroy
    Project.find_by(public_key: params[:public_id]).update(active: false)
    return redirect_to dashboard_path
  end

  def releases
    @facade = Projects::ReleasesFacade.new(params)
  end

  def send_release
    Resque.enqueue(
      Jobs::SendReleaseEmailForProject, params[:project_public_id]
    )
    redirect_to project_releases_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/projects/_new.html.erb
<%= render 'shared/project_visibility_tooltip' %>

<%= render 'shared/modal', id: 'modal', title: 'New Project' do %>
  <%= form_tag projects_path(from_none: params[:from_none]) do %>
    <div class="form-group">
      <%= label_tag :name, 'Project Name', class: 'control-label' %>
      <%= text_field_tag :name, '' , { placeholder: 'Name your project', required: true, class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= label_tag :visibility, 'Type', class: 'control-label' %>
      <%= link_to '#', class: '', style: 'margin-left: 5px', target: '_blank', id: 'visibility-help' do %>
        <i class="fa fa-question-circle"></i>&nbsp
      <% end %>
      <%= select_tag :visibility, options_for_select(['Private', 'Public']),  class: 'form-control'  %>
    </div>
    <div class="form-group">

      <%= button_tag 'Create', class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/projects/inbox.html.erb
<%= render 'shared/project_menu' %>

<% content_for :title do %>
  Inbox
<% end %>

<div id="modal-container"></div>

<% if @facade.project.prompts.empty? && @facade.project.prompt_subscriptions.active.empty? %>
  <%= render 'shared/no_prompts_instruction' %>
<% else %>
  <%= render 'shared/prompts_menu' %>
  <%= render 'shared/pushes_table', show_delete: true, show_create_release: true, show_revert: false %>
<% end %>

app/views/projects/index.html.erb
<%= render 'shared/dash_menu' %>
<div id="modal-container"></div>

<% content_for :title do %>
  Projects
<% end %>

<div style="text-align: right">
  <%= link_to 'Create Project', new_project_path, remote: true, class: 'btn btn-primary' %>
</div>

<table class="rr-table">
  <thead>
    <th>Name</th>
    <th></th>
    <th></th>
  </thead>
  <% @facade.projects.each do |project| %>
    <tr>
      <td><%= project.title.truncate(50) %></td>
      <% unread = @facade.unread_counts[project.id] %>
    </tr>
  <% end %>
</table>

app/views/projects/new.js.erb
$('#modal-container').html("<%= j render 'new' %>");
MicroModal.show('modal-1');

app/views/projects/releases.html.erb
<div id="modal-container"></div>

<% content_for :title do %>
  <%= @facade.project.title.truncate(50) %>
<% end %>

<%= render 'shared/project_menu' %>

<% if @facade.releases.any? %>
  <div class="row">
    <div class="col-md-12">
      <div style="display: flex; justify-content: space-between; align-items: center; ">

        <h2>All Releases</h2>

        <div>
          <%= link_to new_project_release_path, class: 'btn btn-secondary', style: 'margin-left: 9px', id: 'create-release' do %>
            <i class="fas fa-plus"></i>&nbsp
            Create Release
          <% end %>
        </div>

      </div>
    </div>
  </div>

  <table class="rr-table">
    <thead>
      <th width="20%">Date</th>
      <th>Title</th>
      <th>Category</th>
      <th>Author</th>
      <th></th>
    </thead>
    <% @facade.releases.each do |release| %>
      <tr style="<%= release.draft? ? 'color: #b0b0b0;' : nil %>">
        <td><%= release.created_at %></td>
        <td>
          <% if release.draft? %>
            <span class="draft-indicator">Draft</span>
          <% end %>
          <%= release.title.truncate(50) %>
        </td>
        <td><%= release.category ? release.category.title : '-' %></td>
        <td><%= release.user.full_name %></td>
        <td>
          <%= link_to edit_project_release_path(public_id: release.public_key), method: :get  do %>
            <i class="fas fa-search"></i>
          <% end %>
        </td>

      </tr>
    <% end %>
  </table>
<% else %>
  <div style="text-align: center;">
    <h3>
      Create your first Release
    </h3>

    <p>Get started by adding some Releases for your audience.</p> <p>These will be visible on the <strong><%= @facade.project.title %></strong> feed. </p>
  </br>

  <%= link_to new_project_release_path, class: 'btn btn-secondary', style: 'margin-left: 9px', id: 'create-release' do %>
    <i class="fas fa-plus"></i>&nbsp
    Create Release
  <% end %>
  </div>
<% end %>